'use client';
import {useState,useEffect,useRef,useEffectEvent,useSyncExternalStore} from 'react';
import {Battlefield} from '@/components/game3d/Battlefield';
import {deriveReveal,REVEAL_MS,type Reveal} from '@/components/game3d/arena-math';
import {ArrowUpRight,ChevronRight,Shield,Swords,HelpCircle,Check,Copy,Users,Sparkles} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {initial,view,defaults,resolve,bot,reachable,STATS,W,H,shell,same,objective,type Game,type Team,type Order,type Pos} from '@/lib/game/engine';
type Room={code:string;team:Team;game:Game;joined:boolean;ready:boolean;opponentReady:boolean;version:number;token?:string};
const skinNames=['Tideglass','Eclipse','Relic'];
const motionQuery='(prefers-reduced-motion: reduce)';
function subscribeMotion(change:()=>void){const query=matchMedia(motionQuery);query.addEventListener('change',change);return()=>query.removeEventListener('change',change);}
function Portrait({kind,skin=0}: {kind:string;skin?:number}){return <span className={`portrait ${kind.toLowerCase()} ${kind==='Rookit'?'skin-'+skin:''}`} aria-hidden="true"/>}
export default function Home(){
 const [screen,setScreen]=useState<'home'|'battle'>('home'),[game,setGame]=useState<Game>(initial),[team,setTeam]=useState<Team>(0),[selected,setSelected]=useState('0-0'),[orders,setOrders]=useState<Order[]>([]),[mode,setMode]=useState<'move'|'strike'>('move'),[room,setRoom]=useState<Room|null>(null),[token,setToken]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[dialog,setDialog]=useState<'help'|'rooms'|'skins'|'leave'|null>(null),[code,setCode]=useState(''),[skin,setSkin]=useState(0),[copied,setCopied]=useState(false),[resume,setResume]=useState<{code:string;token:string}|null>(null);
 const [reveal,setReveal]=useState<Reveal|null>(null),revealTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const reducedMotion=useSyncExternalStore(subscribeMotion,()=>matchMedia(motionQuery).matches,()=>false);
 const roundRef=useRef(1),pollRef=useRef(false),versionRef=useRef(-1);const visible=room?game:view(game,team);const own=game.units.filter(u=>u.team===team);const current=own.find(u=>u.id===selected);const activeOrder=orders.find(o=>o.id===selected);const canEdit=!busy&&!reveal&&!room?.ready&&game.winner===null;const destinations=current&&canEdit?reachable(current):[];
 // One-time hydration from browser storage; these values intentionally have SSR defaults.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{try{const s=Number(localStorage.getItem('opal-skin'));if([0,1,2].includes(s))setSkin(s);const r=sessionStorage.getItem('opal-room');if(r)setResume(JSON.parse(r))}catch{}},[]);
 useEffect(()=>()=>{if(revealTimer.current)clearTimeout(revealTimer.current)},[]);
 function cancelReveal(){if(revealTimer.current)clearTimeout(revealTimer.current);revealTimer.current=null;setReveal(null)}
 const stopMotion=useEffectEvent(()=>cancelReveal());
 useEffect(()=>{const query=matchMedia(motionQuery);const changed=()=>{if(query.matches)stopMotion()};query.addEventListener('change',changed);return()=>query.removeEventListener('change',changed)},[]);
 function animate(nextVisible:Game,viewer:Team){cancelReveal();if(reducedMotion)return;setReveal(deriveReveal(visible,nextVisible,viewer,orders,performance.now()));revealTimer.current=setTimeout(()=>{setReveal(null);revealTimer.current=null},REVEAL_MS)}
 function accept(r:Room,credential?:string){if(!credential&&r.version<versionRef.current)return;if(credential)cancelReveal();else if(r.game.round>roundRef.current)animate(r.game,r.team);versionRef.current=r.version;setRoom(r);setGame(r.game);setTeam(r.team);if(credential){setToken(credential);sessionStorage.setItem('opal-room',JSON.stringify({code:r.code,token:credential}));setSelected(`${r.team}-0`)}if(roundRef.current!==r.game.round||credential){roundRef.current=r.game.round;setOrders(defaults(r.game,r.team));setMode('move')}setScreen('battle')}
 const acceptPolled=useEffectEvent((r:Room)=>accept(r));
 async function api(body:Record<string,unknown>,credential=token){const res=await fetch('/api/rooms',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${credential}`},body:JSON.stringify(body)});const data=await res.json() as Room & {error?:string};if(!res.ok)throw Error(data.error||'Connection failed. Try again.');return data as Room}
 const roomCode=room?.code;
 useEffect(()=>{if(!roomCode||!token||screen!=='battle')return;let disposed=false;async function poll(){if(pollRef.current)return;pollRef.current=true;try{const res=await fetch(`/api/rooms?code=${roomCode}`,{headers:{Authorization:`Bearer ${token}`}});const data=await res.json() as Room & {error?:string};if(!res.ok)throw Error(data.error);if(!disposed){acceptPolled(data);setError('')}}catch(e){if(!disposed)setError(e instanceof Error?e.message:'Reconnecting…')}finally{pollRef.current=false}}const timer=setInterval(poll,1600);return()=>{disposed=true;clearInterval(timer)}},[roomCode,token,screen]);
 function training(){cancelReveal();versionRef.current=-1;const g=initial();setRoom(null);setToken('');setGame(g);setTeam(0);setSelected('0-0');setOrders(defaults(g,0));roundRef.current=1;setMode('move');setScreen('battle');setError('');setDialog(null)}
 async function openRoom(action:'create'|'join'){setBusy(true);setError('');try{const r=await api({action,code});accept(r,r.token);setDialog(null)}catch(e){setError(e instanceof Error?e.message:'Could not connect.')}finally{setBusy(false)}}
 async function resumeRoom(){if(!resume)return;setBusy(true);try{const res=await fetch(`/api/rooms?code=${resume.code}`,{headers:{Authorization:`Bearer ${resume.token}`}});const r=await res.json() as Room & {error?:string};if(!res.ok)throw Error(r.error);accept(r,resume.token);setError('')}catch(e){setError(e instanceof Error?e.message:'Could not resume.');setResume(null);sessionStorage.removeItem('opal-room')}finally{setBusy(false)}}
 function updateOrder(changes:Partial<Order>){setOrders(prev=>prev.map(o=>o.id===selected?{...o,...changes}:o))}
 function tile(p:Pos){if(!canEdit||!current?.hp)return;const unit=visible.units.find(u=>u.hp>0&&same(u,p));if(unit?.team===team){if(unit.id===selected)updateOrder({to:p});setSelected(unit.id);setMode('move');return}if(mode==='strike'&&unit&&unit.team!==team){updateOrder({action:'strike',target:unit.id});setMode('move');return}if(mode==='move'&&destinations.some(d=>same(d,p)))updateOrder({to:p})}
 async function lock(){if(!canEdit)return;setBusy(true);setError('');try{if(room){const r=await api({action:'orders',code:room.code,round:game.round,orders});accept(r)}else{const next=resolve(game,orders,bot(game,1));animate(view(next,team),team);setGame(next);setOrders(defaults(next,0));setMode('move')}}catch(e){setError(e instanceof Error?e.message:'Could not resolve turn.')}finally{setBusy(false)}}
 async function leave(){if(room&&game.winner===null){setBusy(true);try{await api({action:'forfeit',code:room.code})}catch(e){setError(e instanceof Error?e.message:'Could not leave.');setBusy(false);return}setBusy(false)}cancelReveal();setScreen('home');setRoom(null);setDialog(null);setError('');setResume(null);sessionStorage.removeItem('opal-room')}
 async function copy(){try{await navigator.clipboard.writeText(room?.code??'');setCopied(true);setTimeout(()=>setCopied(false),1500)}catch{setError('Select and copy the room code shown above.')}}
 const readPermittedState=useEffectEvent(()=>({screen,team,game:visible,orders,selected,legalDestinations:destinations}));
 useEffect(()=>{const nav=navigator as Navigator&{modelContext?:{registerTool:(t:unknown)=>void;unregisterTool:(s:string)=>void}};if(!nav.modelContext)return;nav.modelContext.registerTool({name:'opal_shift_state',description:'Read the current Opal Shift duel, visible creatures and legal destinations. No hidden opponent information.',inputSchema:{type:'object',properties:{}},execute:async()=>({content:[{type:'text',text:JSON.stringify(readPermittedState())}]})});return()=>nav.modelContext?.unregisterTool('opal_shift_state')},[]);
 const matchEnded=game.winner!==null&&!reveal;
 return <main className={screen==='home'?'lobby':'game-shell'}>
 <header><button className="brand" onClick={()=>screen==='battle'?setDialog('leave'):setScreen('home')} aria-label="Opal Shift home">OPAL <i>SHIFT</i><span className="brand-dot">✦</span></button><nav><span className="alpha">PLAYABLE ALPHA <b>01</b></span><button className="icon-button" onClick={()=>setDialog('help')} aria-label="How to play"><HelpCircle size={19}/></button></nav></header>
 {screen==='home'?<>
 <section className="lobby-content"><p className="eyebrow"><span className="live-dot"/> A NEW KIND OF RIVALRY</p><h1>Small creatures.<br/>Big instincts.</h1><p className="intro">Outthink your rival on the Opal Coast.<br/>A three-creature duel where every move matters.</p><div className="home-actions"><button className="primary large" onClick={training}>Play training <ArrowUpRight size={20}/></button><button className="glass large" onClick={()=>{setDialog('rooms');setError('')}}><Users size={18}/> Private duel</button></div><p className="micro">1 versus 1 · Simultaneous turns · First to 3</p>{resume&&<button className="resume" disabled={busy} onClick={resumeRoom}>Resume room {resume.code} <ChevronRight size={16}/></button>}{error&&<p className="error" role="alert">{error}</p>}</section>
 <footer className="lobby-footer"><div><span className="eyebrow">01 / THE OPAL COAST</span><p>Find your opening. Make your shift.</p></div><button className="collection-link" onClick={()=>setDialog('skins')}><span className="mini-art"/><span><small>YOUR CREATURES</small><strong>Meet your squad</strong></span><ArrowUpRight size={19}/></button></footer>
 </>:<>
 <div className="battle-heading"><div><p className="eyebrow">{room?`PRIVATE DUEL / ${room.code}`:'TRAINING / OPAL COAST'}</p><h1>The Shellwilds <span>01</span></h1></div><div className="scoreboard"><div className={team===0?'you mint':'mint'}><span>MINT {team===0?'· YOU':''}</span><strong>{game.score[0]}</strong></div><span className="score-divider">✦<small>FIRST TO 3</small></span><div className={team===1?'you coral':'coral'}><span>CORAL {team===1?'· YOU':''}</span><strong>{game.score[1]}</strong></div></div></div>
 <div className="battle-layout"><section className="arena-section" aria-label="Duel arena"><div className="arena-toolbar"><span><span className="live-dot"/>{busy||reveal?'RESOLVING':room?.ready?'ORDERS LOCKED':matchEnded?'DUEL COMPLETE':'PLAN YOUR SHIFT'}</span><span>TURN {Math.min(game.round,12)} <em>/ 12</em></span></div>
 <Battlefield game={visible} team={team} selected={selected} orders={orders} destinations={destinations} mode={mode} canEdit={canEdit} skin={skin} reveal={reducedMotion?null:reveal} reducedMotion={reducedMotion} onTile={tile}>
 <div className="arena" role="group" aria-label="15 by 11 battlefield. Select a creature, then a highlighted tile to move.">
 <div className="root root-a"/><div className="root root-b"/><div className="root root-c"/>
 {Array.from({length:W*H},(_,i)=>{const p={x:i%W,y:Math.floor(i/W)},s=shell(p),u=visible.units.find(u=>u.hp>0&&same(u,p)),planned=orders.find(o=>same(o.to,p)&&!same(o.to,own.find(u=>u.id===o.id)??o.to)),reachableHere=destinations.some(d=>same(d,p)),chosen=activeOrder&&same(activeOrder.to,p);return <button key={i} onClick={()=>tile(p)} disabled={s||!canEdit} className={`tile ${s?'shell-tile':''} ${objective(p)?'prism-tile':''} ${reachableHere&&mode==='move'?'reachable':''} ${chosen?'destination':''} ${u?'occupied':''}`} style={{gridColumn:p.x+1,gridRow:p.y+1}} aria-label={`${p.x+1}, ${p.y+1}${s?', shell cover':''}${objective(p)?', prism zone':''}${u?`, ${u.team===team?'your':'opponent'} ${u.kind}, ${u.hp} health`:''}${reachableHere?', reachable':''}`}>
 {s&&<span className="shell-art"/>}{same(p,{x:7,y:5})&&!u&&<span className="prism">◆</span>}{planned&&!u&&<span className="ghost">{planned.id.slice(-1)==='0'?'V':planned.id.slice(-1)==='1'?'R':'K'}</span>}
 {u&&<span className={`piece ${u.team===0?'mint-piece':'coral-piece'} ${u.id===selected?'selected':''}`}><Portrait kind={u.kind} skin={u.team===team?skin:0}/><span className="piece-letter">{u.kind[0]}</span><span className="health-track"><span style={{width:`${u.hp/STATS[u.kind].hp*100}%`}}/></span>{orders.find(o=>o.id===u.id)?.action==='guard'&&u.team===team&&<Shield className="guard-icon" size={10}/>}</span>}
 </button>})}</div>
 </Battlefield>
 <div className="arena-caption"><span><i className="legend mint-bg"/>Your squad is {team===0?'mint':'coral'} · {own.filter(u=>u.hp>0).length}/3 active</span><span><span className="legend-diamond">◆</span> Hold the prism uncontested</span><span>◎ Shells block sight & strikes</span></div>
 <div className="combat-log" aria-live="polite"><span className="eyebrow">{game.round===1?'FIELD NOTES':'LAST SHIFT'}</span><p>{game.log.join(' ')}</p></div>
 </section><aside className="command-panel"><div className="panel-title"><span className="eyebrow">YOUR SQUAD</span><button className="text-button" onClick={()=>setDialog('skins')}>Skins <Sparkles size={13}/></button></div><h2>Make your move.</h2><p className="panel-description">Set a destination and action for each creature. Both squads move together.</p>
 <div className="squad-list">{own.map(u=>{const o=orders.find(o=>o.id===u.id);return <button key={u.id} className={`squad-card ${selected===u.id?'active':''}`} onClick={()=>{setSelected(u.id);setMode('move')}}><Portrait kind={u.kind} skin={skin}/><span className="creature-info"><strong>{u.kind}<small>{STATS[u.kind].role}</small></strong><span>{u.hp?`${u.hp}/${STATS[u.kind].hp} HP · ${o?.action==='strike'?'Strike':'Guard'}${o&&!same(o.to,u)?` → ${o.to.x+1},${o.to.y+1}`:''}`:'Recovering · returns next shift'}</span></span>{selected===u.id?<span className="selected-dot"/>:<ChevronRight size={16}/>}</button>})}</div>
 {current&&<div className="order-editor"><div className="editor-heading"><strong>{current.kind}&apos;s orders</strong><span>MOVE {STATS[current.kind].move} · RANGE {STATS[current.kind].range}</span></div><p className="instruction">{!current.hp?'This creature returns next turn.':mode==='strike'?'Tap a visible rival to target, or use auto-target.':'Tap a lit tile to plan movement.'}</p><div className="order-buttons"><button disabled={!canEdit||!current.hp} className={activeOrder?.action==='guard'?'active':''} onClick={()=>{updateOrder({action:'guard',target:undefined});setMode('move')}}><Shield size={17}/> Guard</button><button disabled={!canEdit||!current.hp} className={activeOrder?.action==='strike'?'active':''} onClick={()=>{updateOrder({action:'strike',target:undefined});setMode('strike')}}><Swords size={17}/> Strike</button></div><p className="action-detail">{activeOrder?.action==='strike'?activeOrder.target?`Target: ${visible.units.find(u=>u.id===activeOrder.target)?.kind??'rival'}. Hits only if in range after movement.`:'Auto-target: nearest visible rival in range after movement.':`Block 1 damage from each hit after moving.`}</p>{mode==='strike'&&<button className="text-button" onClick={()=>setMode('move')}>Auto-target selected · choose movement</button>}</div>}
 <div className="lock-area">{room&&!room.joined?<div className="waiting"><p>Invite your rival</p><button onClick={copy}><strong>{room.code}</strong>{copied?<Check size={18}/>:<Copy size={18}/>}</button><small>They need access to this app, then choose Private duel → Join.</small></div>:<><button className="primary lock-button" disabled={!canEdit} onClick={lock}>{busy||reveal?'Revealing shift…':room?.ready?'Waiting for rival…':'Lock in orders'}{!busy&&!room?.ready&&<ArrowUpRight size={19}/>}</button><p className="micro">{room?(room.opponentReady?'Rival has locked their orders.':'Your orders stay secret until both players lock.'):'Take your time. The training rival is ready.'}</p></>}{error&&<p className="error" role="alert">{error}</p>}</div>
 </aside></div>
 {matchEnded&&<div className="result-banner" role="status"><div><p className="eyebrow">THE COAST REMEMBERS</p><h2>{game.winner==='draw'?'A perfect standoff.':game.winner===team?'Beautifully played.':'A rivalry worth another round.'}</h2><p>{game.winner==='draw'?'Draw':game.winner===team?'Victory':'Defeat'} · Mint {game.score[0]} — Coral {game.score[1]}</p></div><button className="primary" onClick={room?()=>leave():training}>{room?'Return to coast':'Play again'} <ArrowUpRight size={18}/></button></div>}
 </>}
 <Dialog open={dialog!==null} onOpenChange={o=>{if(!o)setDialog(null)}}><DialogContent className={dialog==='skins'?'skin-dialog':''}><DialogTitle>{dialog==='help'?'How to make your shift':dialog==='rooms'?'A coast for two':dialog==='skins'?'A little wild. Entirely yours.':'Leave this duel?'}</DialogTitle><DialogDescription>{dialog==='help'?'A quick guide to your first duel.':dialog==='rooms'?'Create a private room or join a friend with their six-character code.':dialog==='skins'?'Meet the launch squad and try three Rookit skins. All are available in this alpha.':room?'Leaving awards the win to your opponent.':'Your training match will be reset.'}</DialogDescription>
 {dialog==='help'&&<div className="rules"><p><b>01 · Plan together</b>Select each creature, tap a reachable tile, then choose Guard or Strike. You can move and act in the same turn.</p><p><b>02 · Read your rival</b>Lock your orders. Both squads move, then attack simultaneously. A named target can escape; auto-target picks the nearest visible rival. Contested landing tiles cancel movement.</p><p><b>03 · Own the prism</b>Finish a turn with a creature on the five glowing center tiles and no opponent there to earn 1 point. First to 3 wins. After 12 turns, higher score wins; ties draw.</p><p><b>04 · Work the shells</b>Shells block movement and line of sight. Adjacent creatures hide from enemies more than 2 tiles away. Guard reduces each hit by 1. Knocked-out creatures return next turn.</p><p className="micro">Training has no timer. Private matches wait for both players. Skins never change stats.</p><button className="primary" onClick={()=>setDialog(null)}>Got it <Check size={17}/></button></div>}
 {dialog==='rooms'&&<div className="room-form"><button className="primary" disabled={busy} onClick={()=>openRoom('create')}>{busy?'Connecting…':'Create a room'}<ArrowUpRight size={18}/></button><div className="divider">OR JOIN A RIVAL</div><label htmlFor="room-code">Room code</label><div className="join-row"><input id="room-code" placeholder="ABC234" value={code} maxLength={6} autoCapitalize="characters" onChange={e=>setCode(e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,''))}/><button disabled={busy||code.length!==6} onClick={()=>openRoom('join')}>Join <ChevronRight size={17}/></button></div><p className="micro">Rooms last 24 hours. Keep this browser tab to retain your seat. Both players need access to the app.</p>{error&&<p className="error" role="alert">{error}</p>}</div>}
 {dialog==='skins'&&<div className="collection"><div className="collection-roster">{(['Veyl','Rookit','Klyra']as const).map(kind=><div key={kind}><Portrait kind={kind} skin={skin}/><strong>{kind}</strong><small>{STATS[kind].role}</small><p>{kind==='Veyl'?'Quick feet. Sharp instincts.':kind==='Rookit'?'A stubborn heart in an opal shell.':'A quiet scout with a long reach.'}</p></div>)}</div><div className="skin-header"><span className="eyebrow">ROOKIT / COSMETIC SKINS</span><span>Equal stats. Different energy.</span></div><div className="skin-options">{skinNames.map((name,i)=><button key={name} className={skin===i?'equipped':''} onClick={()=>{setSkin(i);localStorage.setItem('opal-skin',String(i))}}><span className={`skin-art skin-${i}`}/><strong>{name}</strong><small>{skin===i?'✓ Equipped':'Equip skin'}</small></button>)}</div><p className="micro">Your appearance preference is saved on this device. Collection progression and purchases are planned for a later release.</p></div>}
 {dialog==='leave'&&<div className="home-actions"><button onClick={()=>setDialog(null)}>Keep playing</button><button className="primary" disabled={busy} onClick={leave}>Leave duel</button></div>}
 </DialogContent></Dialog>
 </main>
}
