export type Team = 0 | 1;
export type Pos = {x:number;y:number};
export type Kind = 'Veyl'|'Rookit'|'Klyra';
export type Unit = Pos & {id:string;team:Team;kind:Kind;hp:number;respawn:number};
export type Order = {id:string;to:Pos;action:'strike'|'guard';target?:string};
export type Game = {round:number;score:[number,number];units:Unit[];winner:Team|'draw'|null;log:string[]};
export const W=15,H=11;
export const SHELLS:Pos[]=[{x:4,y:2},{x:4,y:3},{x:10,y:7},{x:10,y:8},{x:5,y:7},{x:9,y:3},{x:7,y:2},{x:7,y:8}];
export const STATS:Record<Kind,{hp:number;move:number;range:number;damage:number;role:string}>={Veyl:{hp:5,move:3,range:2,damage:2,role:'Flanker'},Rookit:{hp:7,move:2,range:2,damage:2,role:'Defender'},Klyra:{hp:4,move:3,range:4,damage:1,role:'Scout'}};
export const distance=(a:Pos,b:Pos)=>Math.abs(a.x-b.x)+Math.abs(a.y-b.y);
export const same=(a:Pos,b:Pos)=>a.x===b.x&&a.y===b.y;
export const inside=(p:Pos)=>Number.isInteger(p.x)&&Number.isInteger(p.y)&&p.x>=0&&p.x<W&&p.y>=0&&p.y<H;
export const shell=(p:Pos)=>SHELLS.some(s=>same(s,p));
export const objective=(p:Pos)=>distance(p,{x:7,y:5})<=1;
export function initial():Game{return {round:1,score:[0,0],winner:null,log:['Hold the prism uncontested to earn 1 point. First to 3 wins.'],units:([0,1] as Team[]).flatMap(team=>(['Veyl','Rookit','Klyra'] as Kind[]).map((kind,i)=>({id:`${team}-${i}`,team,kind,hp:STATS[kind].hp,respawn:0,x:team===0?1:13,y:3+i*2})))}}
export function reachable(u:Unit):Pos[]{if(!u.hp)return [];const seen=new Set([`${u.x},${u.y}`]),queue=[{x:u.x,y:u.y,n:0}],out:Pos[]=[];while(queue.length){const p=queue.shift()!;out.push({x:p.x,y:p.y});if(p.n>=STATS[u.kind].move)continue;for(const [dx,dy]of [[0,1],[1,0],[0,-1],[-1,0]]){const q={x:p.x+dx,y:p.y+dy},key=`${q.x},${q.y}`;if(inside(q)&&!shell(q)&&!seen.has(key)){seen.add(key);queue.push({...q,n:p.n+1})}}}return out}
export function lineOfSight(a:Pos,b:Pos){const n=Math.max(Math.abs(b.x-a.x),Math.abs(b.y-a.y))*4;for(let i=1;i<n;i++){const p={x:Math.round(a.x+(b.x-a.x)*i/n),y:Math.round(a.y+(b.y-a.y)*i/n)};if(!same(p,a)&&!same(p,b)&&shell(p))return false}return true}
export function hidden(u:Unit,g:Game,viewer:Team){return u.team!==viewer&&u.hp>0&&SHELLS.some(s=>distance(s,u)===1)&&!g.units.some(a=>a.team===viewer&&a.hp>0&&distance(a,u)<=2&&lineOfSight(a,u))}
export function view(g:Game,team:Team):Game{return {...g,units:g.units.filter(u=>!hidden(u,g,team))}}
export function defaults(g:Game,team:Team):Order[]{return g.units.filter(u=>u.team===team&&u.hp>0).map(u=>({id:u.id,to:{x:u.x,y:u.y},action:'guard'}))}
export function validate(g:Game,team:Team,input:unknown):Order[]{if(!Array.isArray(input)||input.length>3)throw Error('Invalid squad orders.');const owned=g.units.filter(u=>u.team===team&&u.hp>0);if(input.length!==owned.length)throw Error('Give every active creature an order.');const ids=new Set<string>();return input.map(o=>{const u=owned.find(u=>u.id===o?.id);if(!u||ids.has(u.id)||!o.to||!reachable(u).some(p=>same(p,o.to))||!['guard','strike'].includes(o.action))throw Error('An order is not legal.');ids.add(u.id);if(o.action==='strike'&&o.target&&!g.units.some(t=>t.id===o.target&&t.team!==team&&t.hp>0&&!hidden(t,g,team)))throw Error('That target is not visible.');return {id:u.id,to:{x:o.to.x,y:o.to.y},action:o.action,...(o.target?{target:o.target}:{})}})}
export function resolve(input:Game,a:Order[],b:Order[]):Game{if(input.winner!==null)return input;const g:Game=structuredClone(input);const orders=[...validate(input,0,a),...validate(input,1,b)];g.log=[];
// Reserve destinations simultaneously. Contested destinations and occupied stationary tiles cancel movement.
const destinations=new Map(orders.map(o=>[o.id,o.to]));let changed=true;while(changed){const blocked=g.units.filter(u=>{const p=destinations.get(u.id)??u;return u.hp>0&&!same(p,u)&&g.units.some(v=>v.hp>0&&v.id!==u.id&&same(destinations.get(v.id)??v,p))});changed=blocked.length>0;for(const u of blocked){destinations.set(u.id,{x:u.x,y:u.y});g.log.push(`${u.kind}'s route was contested.`)}}
for(const u of g.units){if(u.hp>0)Object.assign(u,destinations.get(u.id)??{});else if(u.respawn>0){u.respawn--;if(u.respawn===0){const home={x:u.team===0?1:13,y:3+Number(u.id.slice(-1))*2};const options=[home,...Array.from({length:H},(_,y)=>({x:home.x,y}))];const spawn=options.find(p=>!g.units.some(v=>v.hp>0&&same(v,p)));if(spawn){Object.assign(u,spawn);u.hp=STATS[u.kind].hp;g.log.push(`${u.kind} returned to the coast.`)}else u.respawn=1}}}
const damages=new Map<string,number>();for(const o of orders){const u=g.units.find(u=>u.id===o.id)!;if(!u.hp||o.action!=='strike')continue;const candidates=g.units.filter(v=>v.team!==u.team&&v.hp>0&&distance(u,v)<=STATS[u.kind].range&&lineOfSight(u,v)&&!hidden(v,g,u.team));const target=o.target?candidates.find(v=>v.id===o.target):candidates.sort((a,b)=>distance(u,a)-distance(u,b)||a.hp-b.hp)[0];if(!target){g.log.push(`${u.kind}'s strike found no target.`);continue}const guard=orders.some(t=>t.id===target.id&&t.action==='guard');const reduction=guard?1:0;const damage=Math.max(0,STATS[u.kind].damage-reduction);damages.set(target.id,(damages.get(target.id)??0)+damage);g.log.push(`${u.team===0?'Mint':'Coral'} ${u.kind} hit ${target.kind} for ${damage}${guard?' · guarded':''}.`)}
for(const [id,d]of damages){const u=g.units.find(u=>u.id===id)!;u.hp=Math.max(0,u.hp-d);if(!u.hp){u.respawn=1;g.log.push(`${u.kind} knocked out · returns next turn.`)}}const holding=([0,1]as Team[]).map(t=>g.units.some(u=>u.team===t&&u.hp>0&&objective(u)));if(holding[0]!==holding[1]){const t=holding[0]?0:1;g.score[t]++;g.log.push(`${t===0?'Mint':'Coral'} claimed the prism · +1 point.`)}else g.log.push(holding[0]?'Prism contested · no points.':'Prism unclaimed.');if(g.score[0]>=3||g.score[1]>=3)g.winner=g.score[0]>=3?0:1;else if(g.round>=12)g.winner=g.score[0]===g.score[1]?'draw':g.score[0]>g.score[1]?0:1;g.round++;return g}
export function bot(g:Game,team:Team):Order[]{const v=view(g,team);const used:Pos[]=[];return defaults(g,team).map(o=>{const u=g.units.find(u=>u.id===o.id)!;const enemies=v.units.filter(t=>t.team!==team&&t.hp>0);const candidates=reachable(u).filter(p=>!used.some(q=>same(p,q)));candidates.sort((a,b)=>{const rate=(p:Pos)=>distance(p,{x:7,y:5})*3+(objective(p)?-6:0)-enemies.filter(e=>distance(p,e)<=STATS[u.kind].range&&lineOfSight(p,e)).length*2;return rate(a)-rate(b)});const to=candidates[0]??u;used.push(to);const target=enemies.filter(e=>distance(to,e)<=STATS[u.kind].range&&lineOfSight(to,e)).sort((a,b)=>a.hp-b.hp)[0];return {id:u.id,to:{x:to.x,y:to.y},action:target?'strike':'guard',...(target?{target:target.id}:{})}})}
