import { initial, resolve, validate, view, type Game, type Team } from './engine.ts';
type Row={code:string;state:string;host:string;guest:string|null;orders0:string|null;orders1:string|null;version:number;expires:number};
const hash=async(s:string)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))).map(x=>x.toString(16).padStart(2,'0')).join('');
const token=()=>crypto.randomUUID()+crypto.randomUUID();
const answer=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
export function createRoomHandlers(database:()=>D1Database){
async function row(code:string){return database().prepare('SELECT * FROM rooms WHERE code = ? AND expires > ?').bind(code,Date.now()).first<Row>()}
async function auth(request:Request,r:Row):Promise<Team>{const supplied=request.headers.get('Authorization')?.replace(/^Bearer /,'')??'';const h=await hash(supplied);if(h===r.host)return 0;if(h===r.guest)return 1;throw Error('This seat is not available on this device. Join with a room code.')}
function payload(r:Row,t:Team){return {code:r.code,team:t,game:view(JSON.parse(r.state),t),joined:!!r.guest,ready:!!r[t===0?'orders0':'orders1'],opponentReady:!!r[t===0?'orders1':'orders0'],version:r.version}}
async function GET(req:Request){try{const code=new URL(req.url).searchParams.get('code')?.toUpperCase()??'';const r=await row(code);if(!r)return answer({error:'Room not found or expired.'},404);const t=await auth(req,r);return answer(payload(r,t))}catch(e){return answer({error:e instanceof Error?e.message:'Room unavailable.'},400)}}
async function POST(req:Request){try{const body=await req.json() as Record<string,unknown>;if(!body||typeof body!=='object')throw Error('Invalid request.');if(body.action==='create'){const seat=token();for(let i=0;i<3;i++){const code=Array.from(crypto.getRandomValues(new Uint8Array(6)),n=>'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'[n%31]).join('');const g=initial();const result=await database().prepare('INSERT OR IGNORE INTO rooms (code,state,host,version,expires) VALUES (?,?,?,0,?)').bind(code,JSON.stringify(g),await hash(seat),Date.now()+86400000).run();if(result.meta.changes)return answer({token:seat,...payload((await row(code))!,0)})}throw Error('Could not create a room. Try again.')}
const code=String(body.code??'').trim().toUpperCase();let r=await row(code);if(!r)return answer({error:'Room not found or expired.'},404);
if(body.action==='join'){if(r.guest)throw Error('Both seats are taken. Ask for a new room.');const seat=token();const result=await database().prepare('UPDATE rooms SET guest=?,version=version+1 WHERE code=? AND guest IS NULL').bind(await hash(seat),code).run();if(!result.meta.changes)throw Error('Another player took this seat.');return answer({token:seat,...payload((await row(code))!,1)})}
const team=await auth(req,r);if(body.action==='forfeit'){const game:Game=JSON.parse(r.state);if(game.winner===null){game.winner=team===0?1:0;game.log=['Your opponent left the duel.'];const result=await database().prepare('UPDATE rooms SET state=?,version=version+1 WHERE code=? AND version=?').bind(JSON.stringify(game),code,r.version).run();if(!result.meta.changes)throw Error('The duel updated. Please leave again.')}return answer(payload((await row(code))!,team))}
if(body.action!=='orders')throw Error('Unknown room action.');if(!r.guest)throw Error('Waiting for your opponent to join.');let game:Game=JSON.parse(r.state);if(game.winner!==null)throw Error('This duel has ended.');if(body.round!==game.round)throw Error('The next turn has already started.');const orders=validate(game,team,body.orders);const column=team===0?'orders0':'orders1';const update=await database().prepare(`UPDATE rooms SET ${column}=?,version=version+1 WHERE code=? AND version=? AND ${column} IS NULL`).bind(JSON.stringify(orders),code,r.version).run();if(!update.meta.changes){r=(await row(code))!;if(!r[column])throw Error('Room updated. Please lock your orders again.')}r=(await row(code))!;
if(r.orders0&&r.orders1){game=resolve(JSON.parse(r.state),JSON.parse(r.orders0),JSON.parse(r.orders1));await database().prepare('UPDATE rooms SET state=?,orders0=NULL,orders1=NULL,version=version+1 WHERE code=? AND version=?').bind(JSON.stringify(game),code,r.version).run();r=(await row(code))!}return answer(payload(r,team));
}catch(e){return answer({error:e instanceof Error?e.message:'Could not update the room.'},400)}}

return {GET,POST};
}
